"""
STUDENT-TEACHER PAIRS SCHEMA DEFINITION
For Fine-Tuning Phi-3-mini with Socratic Feedback Generation

File: data/finetune/student_teacher_pairs.jsonl
Format: JSON Lines (one JSON object per line)
Total: 50 synthetic pairs across 18 ML topics

This module defines the schema, validation, and loading utilities for the
fine-tuning dataset used to train the Coach agent (Phi-3-mini with LoRA).
"""

from dataclasses import dataclass
from typing import Optional, List
import json
from datetime import datetime

# ============================================================================
# SCHEMA DEFINITION
# ============================================================================

@dataclass
class StudentTeacherPair:
    """
    Represents one training example for Socratic feedback generation.
    
    The "text" field is formatted with Phi-3 chat template for SFT training.
    """
    
    topic: str
    """Machine Learning topic (e.g., 'Backpropagation')"""
    
    student_work: str
    """
    Transcribed student's handwritten solution.
    Example: "I computed ∂L/∂W = δ · a^T, where δ = ŷ - y."
    """
    
    identified_errors: List[str]
    """
    List of errors identified by the Analyzer agent.
    Example: ["Missing chain rule derivation", "δ only valid for output layer"]
    """
    
    teacher_feedback: str
    """
    Socratic feedback card generated by Coach.
    Should NEVER include the correct answer, only guiding questions.
    Should include hint sections, review topic, and rubric score.
    """
    
    error_severity: str
    """One of: 'minor', 'moderate', 'major' - helps weight training examples"""
    
    correct_elements: Optional[List[str]] = None
    """List of things the student got right (encouragement in feedback)"""
    
    rubric_references: Optional[List[str]] = None
    """List of rubric rule IDs violated (e.g., ['BP_001', 'BP_003'])"""
    
    metadata: Optional[dict] = None
    """Optional metadata: {"unit": "Unit 2", "difficulty": "intermediate", ...}"""
    
    def to_phi3_format(self) -> str:
        """
        Format this pair as a single training example using Phi-3 chat template.
        
        Output format:
        <|system|>You are a Socratic ML tutor...<|end|>
        <|user|>Topic: {topic}\nStudent work: {student_work}\nIdentified errors: {errors}<|end|>
        <|assistant|>{teacher_feedback}<|end|>
        
        Returns:
            A formatted string ready for SFT training.
        """
        
        system_prompt = (
            "You are a Socratic teaching coach for Machine Learning. "
            "Guide students toward understanding without revealing answers. "
            "Ask leading questions that help them discover their own mistakes. "
            "Always reference relevant lecture materials and concepts."
        )
        
        user_input = (
            f"Topic: {self.topic}\n"
            f"Student work: {self.student_work}\n"
            f"Identified errors: {', '.join(self.identified_errors)}"
        )
        
        formatted = (
            f"<|system|>{system_prompt}<|end|>"
            f"<|user|>{user_input}<|end|>"
            f"<|assistant|>{self.teacher_feedback}<|end|>"
        )
        
        return formatted
    
    def to_dict(self) -> dict:
        """Convert to dictionary format for JSON serialization."""
        return {
            "topic": self.topic,
            "student_work": self.student_work,
            "identified_errors": self.identified_errors,
            "teacher_feedback": self.teacher_feedback,
            "error_severity": self.error_severity,
            "correct_elements": self.correct_elements or [],
            "rubric_references": self.rubric_references or [],
            "metadata": self.metadata or {},
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> "StudentTeacherPair":
        """Create instance from dictionary."""
        return cls(
            topic=data.get("topic"),
            student_work=data.get("student_work"),
            identified_errors=data.get("identified_errors", []),
            teacher_feedback=data.get("teacher_feedback"),
            error_severity=data.get("error_severity", "moderate"),
            correct_elements=data.get("correct_elements"),
            rubric_references=data.get("rubric_references"),
            metadata=data.get("metadata"),
        )


# ============================================================================
# JSONL UTILITIES
# ============================================================================

class StudentTeacherDataset:
    """
    Utility class for loading, validating, and processing the fine-tuning dataset.
    """
    
    def __init__(self, jsonl_path: str):
        """
        Initialize dataset from JSONL file.
        
        Args:
            jsonl_path: Path to student_teacher_pairs.jsonl
        """
        self.jsonl_path = jsonl_path
        self.pairs: List[StudentTeacherPair] = []
        self.topic_distribution = {}
    
    def load(self) -> None:
        """Load and parse JSONL file."""
        print(f"Loading dataset from {self.jsonl_path}...")
        
        with open(self.jsonl_path, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                try:
                    data = json.loads(line.strip())
                    pair = StudentTeacherPair.from_dict(data)
                    self.pairs.append(pair)
                    
                    # Track topic distribution
                    topic = pair.topic
                    self.topic_distribution[topic] = self.topic_distribution.get(topic, 0) + 1
                
                except json.JSONDecodeError as e:
                    print(f"⚠️  Error parsing line {line_num}: {e}")
                except Exception as e:
                    print(f"⚠️  Error processing line {line_num}: {e}")
        
        print(f"✓ Loaded {len(self.pairs)} pairs")
        self._print_distribution()
    
    def _print_distribution(self) -> None:
        """Print topic distribution for verification."""
        print("\n📊 Topic Distribution:")
        for topic in sorted(self.topic_distribution.keys()):
            count = self.topic_distribution[topic]
            bar = "█" * count
            print(f"  {topic:.<40} {count:>2} {bar}")
        
        total = sum(self.topic_distribution.values())
        print(f"\n  Total: {total} pairs")
    
    def get_phi3_format_dataset(self) -> List[dict]:
        """
        Convert dataset to Phi-3 chat template format for training.
        
        Returns:
            List of dicts with 'text' field containing formatted training examples.
        """
        formatted = []
        for pair in self.pairs:
            formatted.append({
                "text": pair.to_phi3_format()
            })
        return formatted
    
    def save_formatted_for_training(self, output_path: str) -> None:
        """
        Save dataset in Phi-3 chat template format to a new JSONL file.
        
        Args:
            output_path: Path to save formatted training data.
        """
        formatted = self.get_phi3_format_dataset()
        
        with open(output_path, 'w', encoding='utf-8') as f:
            for example in formatted:
                f.write(json.dumps(example) + '\n')
        
        print(f"✓ Saved {len(formatted)} formatted examples to {output_path}")
    
    def filter_by_topic(self, topic: str) -> List[StudentTeacherPair]:
        """Get all pairs for a specific topic."""
        return [p for p in self.pairs if p.topic == topic]
    
    def filter_by_severity(self, severity: str) -> List[StudentTeacherPair]:
        """Get all pairs with specific error severity."""
        return [p for p in self.pairs if p.error_severity == severity]
    
    def get_statistics(self) -> dict:
        """Return dataset statistics."""
        return {
            "total_pairs": len(self.pairs),
            "topic_distribution": self.topic_distribution,
            "severity_distribution": {
                "minor": len(self.filter_by_severity("minor")),
                "moderate": len(self.filter_by_severity("moderate")),
                "major": len(self.filter_by_severity("major")),
            },
            "avg_error_per_pair": sum(len(p.identified_errors) for p in self.pairs) / len(self.pairs) if self.pairs else 0,
        }


# ============================================================================
# EXAMPLE SCHEMA (REFERENCE)
# ============================================================================

EXAMPLE_PAIR = {
    "topic": "Backpropagation",
    "student_work": (
        "I computed ∂L/∂W = δ · a^T, where δ = ŷ - y. "
        "So the weights update as W = W - α*(ŷ-y)."
    ),
    "identified_errors": [
        "Missing chain rule derivation",
        "δ is only valid for the output layer",
        "No hidden layer gradients computed"
    ],
    "teacher_feedback": (
        "## Feedback Card\n\n"
        "**What you did well:** "
        "You correctly identified that the output layer gradient has the clean form (ŷ - y), "
        "and you applied the weight update direction correctly.\n\n"
        "**Hint 1 (re: Chain Rule):** "
        "Your formula works for the output layer only. For a hidden layer l, "
        "how does the error 'travel back' through the weights W^[l+1]? "
        "Can you write out the chain ∂L/∂W^[l] = ∂L/∂a^[l] · ∂a^[l]/∂z^[l] · ∂z^[l]/∂W^[l] "
        "for each link?\n\n"
        "**Hint 2 (re: Activation Derivative):** "
        "One of those links, ∂a^[l]/∂z^[l], depends on which activation function you're using. "
        "If the activation is sigmoid σ(z), what is its derivative with respect to z?\n\n"
        "**Review:** L2 ANN forward and Backpropagation.pdf — "
        "especially the section on hidden layer delta (δ^[l]) derivation.\n\n"
        "**Rubric Score:** 3/8 points (Ref: Rules BP_001, BP_003, BP_004)"
    ),
    "error_severity": "major",
    "correct_elements": [
        "Correct notation and setup",
        "Valid first derivation step"
    ],
    "rubric_references": ["BP_001", "BP_003", "BP_004"],
    "metadata": {
        "unit": "Unit 2",
        "difficulty": "intermediate",
        "created_at": "2025-04-14",
        "source": "synthetic"
    }
}


# ============================================================================
# VALIDATION UTILITIES
# ============================================================================

def validate_pair(pair_dict: dict) -> tuple[bool, List[str]]:
    """
    Validate a single pair against the schema.
    
    Returns:
        (is_valid, list_of_errors)
    """
    errors = []
    
    required_fields = ["topic", "student_work", "identified_errors", "teacher_feedback", "error_severity"]
    for field in required_fields:
        if field not in pair_dict or not pair_dict[field]:
            errors.append(f"Missing or empty required field: {field}")
    
    if pair_dict.get("error_severity") not in ["minor", "moderate", "major"]:
        errors.append(f"Invalid error_severity: {pair_dict.get('error_severity')}")
    
    # Check for solution leakage
    leakage_keywords = [
        "the answer is", "therefore", "the solution is", "= [", 
        "the correct formula", "solving this gives"
    ]
    feedback = pair_dict.get("teacher_feedback", "").lower()
    if any(kw in feedback for kw in leakage_keywords):
        errors.append("⚠️  Potential solution leakage detected in teacher_feedback")
    
    is_valid = len(errors) == 0
    return is_valid, errors


def validate_jsonl(jsonl_path: str) -> tuple[int, int, List[tuple[int, List[str]]]]:
    """
    Validate entire JSONL file.
    
    Returns:
        (total_lines, valid_count, list_of_errors_with_line_numbers)
    """
    valid_count = 0
    errors_list = []
    
    with open(jsonl_path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            try:
                data = json.loads(line.strip())
                is_valid, errors = validate_pair(data)
                
                if is_valid:
                    valid_count += 1
                else:
                    errors_list.append((line_num, errors))
            
            except json.JSONDecodeError as e:
                errors_list.append((line_num, [f"JSON parse error: {str(e)}"]))
    
    total_lines = line_num
    return total_lines, valid_count, errors_list


# ============================================================================
# QUICK START
# ============================================================================

if __name__ == "__main__":
    print("Student-Teacher Pairs Dataset Schema")
    print("=" * 70)
    print("\nExample entry (JSONL format):")
    print(json.dumps(EXAMPLE_PAIR, indent=2))
    
    print("\n" + "=" * 70)
    print("\nTo load and process dataset:")
    print("""
    from schema import StudentTeacherDataset
    
    dataset = StudentTeacherDataset('data/finetune/student_teacher_pairs.jsonl')
    dataset.load()
    
    # Get statistics
    stats = dataset.get_statistics()
    print(stats)
    
    # Get training format for Unsloth/SFT
    training_data = dataset.get_phi3_format_dataset()
    
    # Save formatted data
    dataset.save_formatted_for_training('data/finetune/formatted_for_training.jsonl')
    """)
